### ISSUE TITLE
Support driver.Valuer interface

### ISSUE THREAD

**Issue by nvx** [sijms/go-ora#293] opened 2023-01-16 01:25 UTC
go-ora currently does not support the `driver.Valuer` interface as per https://pkg.go.dev/database/sql/driver@go1.19.5#Valuer

In issue #194 it was noted that `gopkg.in/guregu/null.v4` did not work for scanning as support for the `sql.Scanner` interface was not implemented and was resolved by implementing it, but it appears that using eg `null.Int` from this package does not work as a query parameter resulting in the following error: `struct parameter only allowed with user defined type (UDT)`

**Comment by nvx** [comment] 2023-01-16 01:38
It looks like `driver.DefaultParameterConverter` is the way that most other drivers handle supporting of the `driver.Valuer` interface. It looks like using it would simplify `ParameterInfo.encodeValue` quite a lot and remove the need to explicitly handle the sql.Null* types.

**Comment by sijms** [comment] 2023-01-20 22:10
I test the code with your suggestion and I found a problem 
```golang
sqlText := `BEGIN
    SELECT VISIT_ID, NAME, VAL, VISIT_DATE INTO :1, :2, :3, :4 FROM GOORA_TEMP_VISIT WHERE VISIT_ID = 1;
END;`
var (
    id   int64
    name string
    val  float64
    date sql.NullTime
)
_, err := conn.Exec(sqlText, sql.Out{Dest: &id}, go_ora.Out{Dest: &name, Size: 200},
		sql.Out{Dest: &val}, sql.Out{Dest: &date})
```
in the code above I need to return time in variable date
date is initialized to nil
when I call Value() it will return nil
here is the problem
**time.Time** is converted to oracle type **DATE**
**nil** is converted to oracle type **NCHAR**

**Comment by nvx** [comment] 2023-01-23 06:41
> in the code above I need to return time in variable date date is initialized to nil when I call Value() it will return nil here is the problem **time.Time** is converted to oracle type **DATE** **nil** is converted to oracle type **NCHAR**

Does this break things in practice? For a background we've been using https://github.com/mattn/go-oci8 for some time now with null.v4 (note that the go-oci8 package has no Go dependencies) and things have been working fine, but we have a desire to switch away from oci8 due to the complexity of having to have the oci8 libraries available at runtime hence checking out go-ora where we ran into these issues.

**Comment by sijms** [comment] 2023-01-23 20:25
ok I review the code in go-oci8 I can add a case for nil value and then switch null type to correctly add the type

**Comment by sijms** [comment] 2023-01-27 21:00
I fix it in version 2.5.25

**Comment by nvx** [comment] 2023-02-01 03:27
Just gotten around to trying out 2.5.25, passing a null.Int as a query parameter still errors out, albeit with a different error message now

```
reflect: call of reflect.Value.IsNil on struct Value
runtime.gopanic:884
reflect.Value.IsNil:1554
github.com/sijms/go-ora/v2.(*ParameterInfo).encodeValue:143
github.com/sijms/go-ora/v2.(*Stmt).NewParam:1522
github.com/sijms/go-ora/v2.(*Stmt).Query:1668
github.com/sijms/go-ora/v2.(*Stmt).QueryContext:1590
github.com/sijms/go-ora/v2.(*Connection).QueryContext:1145
```

Passing the null.Int as a pointer gives `ORA-03115: unsupported network datatype or representation`, but I suspect it's probably not meant to be a pointer (I haven't had to make it a pointer with any other driver, just tried after seeing the IsNill on struct Value error to see if that would help anything).

**Comment by sijms** [comment] 2023-02-02 20:55
fixed in v2.5.26
please test it before close the issue

**Comment by nvx** [comment] 2023-02-06 06:47
> fixed in v2.5.26 please test it before close the issue

Sorry for the slow reply. Tested on v2.5.27 and getting `ORA-03115: unsupported network datatype or representation` now with the non-pointer null.Int{} argument too.

**Comment by sijms** [comment] 2023-02-06 20:58
I test it and ok
can you give example code to test

**Comment by nvx** [comment] 2023-02-07 00:37
> I test it and ok can you give example code to test
> 
> does null.int{} support Valuer interface?

I did a little more testing, looks like it throws the ORA-03115 error only when the value is null. When it's not null the query works.

The following is a complete example that shows the error:

```
package main

import (
	"database/sql"
	_ "github.com/sijms/go-ora/v2"
	"gopkg.in/guregu/null.v4"
	"os"
)

func main() {
	db, err := sql.Open("oracle", os.Getenv("DSN"))
	if err != nil {
		panic(err)
	}

	rows, err := db.Query(`SELECT 1 FROM DUAL WHERE :1 IS NULL`, null.Int{})
	if err != nil {
		panic(err)
	}
	defer rows.Close()
}
```

Note if you change `null.Int{}` to `null.IntFrom(1234)` so it's not a null value the error goes away.

**Comment by sijms** [comment] 2023-02-07 16:39
I test the code
the problem is "how can the driver detect the type of the input parameter if it is structure and its valuer interface return nil" ?
i solve it as input parameter
```golang
if tempVal == nil {
	switch val.(type) {
	case sql.NullInt32:
		par.setForNumber()
	case sql.NullBool:
		par.setForNumber()
	case sql.NullTime:
		par.setForTime()
	case sql.NullByte:
		par.setForNumber()
	case sql.NullFloat64:
		par.setForNumber()
	case sql.NullInt16:
		par.setForNumber()
	case sql.NullInt64:
		par.setForNumber()
	case sql.NullString:
		par.encodeString("", nil, size)
	case NullNVarChar:
		par.CharsetForm = 2
		par.CharsetID = connection.tcpNego.ServernCharset
		par.encodeString("", nil, size)
	case NullTimeStamp:
		par.setForTime()
		par.DataType = TIMESTAMP
	case *sql.NullInt32:
		par.setForNumber()
	case *sql.NullBool:
		par.setForNumber()
	case *sql.NullTime:
		par.setForTime()
	case *sql.NullByte:
		par.setForNumber()
	case *sql.NullFloat64:
		par.setForNumber()
	case *sql.NullInt16:
		par.setForNumber()
	case *sql.NullInt64:
		par.setForNumber()
	case *sql.NullString:
		par.encodeString("", nil, size)
	case *NullNVarChar:
		par.CharsetForm = 2
		par.CharsetID = connection.tcpNego.ServernCharset
		par.encodeString("", nil, size)
	case *NullTimeStamp:
		par.setForTime()
		par.DataType = TIMESTAMP
	default: // i add this default case for other types
		par.encodeString("", nil, size)
	}
}
```
but if used as output it will give `ORA-06502: PL/SQL: numeric or value error: character string buffer too small`

**Comment by nvx** [comment] 2023-02-07 23:55
> could you test it in last commit before release

This seems to work now!

> but if used as output it will give `ORA-06502: PL/SQL: numeric or value error: character string buffer too small`

What do you mean by this though? I did a quick test doing rows.Scan() into a null.Int both when the value from the database was a number, as well as when it was null and it scanned without issues both times. Or do you mean if calling a procedure with the placeholder as an output? If so I've never tried this with other drivers, so it may be the same there anyway.

**Comment by sijms** [comment] 2023-02-08 09:52
I mean using as output parameter like 
```sql
BEGIN
     SELECT SYSDATE INTO :1 FROM DUAL;
END;
```
then you pass `sql.Out{Dest: &null.Time{}}`

**Closed** 2023-02-10 12:38 UTC

**Comment by nvx** [comment] 2023-02-13 00:33
Ah that's fine, I'm not sure if that worked in other libraries either.
