### ISSUE TITLE
err msg "ORA-24381: error(s) in array DML\n" caused when using bulkinsert...

### ISSUE THREAD

**Issue by j38890** [sijms/go-ora#189] opened 2022-04-25 13:02 UTC
1、table create sql:
======================
CREATE TABLE "COMM_APG_TEST"."GOORA_TEMP_VISIT" 
   (	"VISIT_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(200), 
	"VAL" NUMBER(10,2), 
	"VISIT_DATE" DATE, 
	"MAJOR" VARCHAR2(100)
   ) 

2、code:
=======================
sqlText := `INSERT INTO GOORA_TEMP_VISIT(VISIT_ID, NAME, VAL, VISIT_DATE, MAJOR) VALUES(:1, :2, :3, :4, :5)`
	rowNum := 2
	visitID := make([]driver.Value, rowNum)
	nameText := make([]driver.Value, rowNum)
	val := make([]driver.Value, rowNum)
	date := make([]driver.Value, rowNum)
	major := make([]driver.Value, rowNum)
	initalVal := 1.1
	for index := 0; index < rowNum; index++ {
		visitID[index] = (int64)(index + 1)
		if index == 0 {
			nameText[index] = "M130201_01"
		} else {
			nameText[index] = "S170101_01"
		}
		val[index] = initalVal
		date[index] = time.Now().AddDate(0, index, 0)
		initalVal += 1.1
		if index == 0 {
			major[index] = "M-13" <==========
		} else {
			major[index] = "SP-17"  <==========
		}
		//if index%5 == 0 {
		//	_, err = stmt.Exec(index, nameText, val, nil)
		//} else {
		//	_, err = stmt.Exec(index, nameText, val, time.Now())
		//}
		//if err != nil {
		//	return err
		//}
		//val += 1.1
	}
	result, err := conn.BulkInsert(sqlText, rowNum, visitID, nameText, val, date, major)
	if err != nil {
		return err
	}

3、err returned by code snippet witch in "func (session *Session) readPacket() (PacketInterface, error) {"
========
for loop {
			msg, err := session.GetByte()
			if err != nil {
				return nil, err
			}
			switch msg {
			case 4:
				loop = false
				session.Summary, err = NewSummary(session)
				if err != nil {
					return nil, err
				}
				if session.HasError() {
					return nil, session.GetError() <=======
				}

4、bulk insert success when i replace the value of field to ...
======
if index == 0 {
			major[index] = "M-13" <==========
		} else {
			major[index] = "S-17"  <==========
		}

**Comment by sijms** [comment] 2022-04-26 17:15
I am busy this week I will investigate the issue at the end of the week and inform you

**Comment by j38890** [comment] 2022-04-27 02:27
thanks a lot.
go-ora is a excellent project, i have used it in production environment.
hope your solution for bulk insert.
thx again.

**Comment by rolson-alister** [comment] 2022-04-27 18:13
Greetings!

I have a similar problem: I constantly get an error like ORA-24381.

I noticed one interesting feature: if I execute the code using Bulk Insert many times, after some time it will still be executed without errors and the insertion of rows will be successful. Very strange behavior. But in 98 percent of cases, I always get the error ORA-24381.

**Comment by sijms** [comment] 2022-04-30 03:07
I test the code working:
I don't know where is the problem but I will share my code:
please confirm the column size is big enough for data and if column is not null don't pass null value into it 
database charset is important also some charset take 2 or 3 byte for character
```Golang
func createTable(conn *sql.DB) error {
	t := time.Now()
	sqlText := `CREATE TABLE GOORA_TEMP_VISIT(
	VISIT_ID	number(10)	NOT NULL,
	NAME		VARCHAR2(200),
	VAL			number(10,2),
	VISIT_DATE	date,
	MAJOR     VARCHAR2(100),
	PRIMARY KEY(VISIT_ID)
	)`
	_, err := conn.Exec(sqlText)
	if err != nil {
		return err
	}
	fmt.Println("Finish create table GOORA_TEMP_VISIT :", time.Now().Sub(t))
	return nil
}
```

Bulk insert function:
```Golang
func bulkInsert(databaseUrl string) error {
	conn, err := go_ora.NewConnection(databaseUrl)
	if err != nil {
		return err
	}
	err = conn.Open()
	if err != nil {
		return err
	}
	defer func() {
		err = conn.Close()
		if err != nil {
			fmt.Println("Can't close connection: ", err)
		}
	}()
	t := time.Now()
	sqlText := `INSERT INTO GOORA_TEMP_VISIT(VISIT_ID, NAME, VAL, VISIT_DATE) VALUES(:1, :2, :3, :4)`
	rowNum := 100
	visitID := make([]driver.Value, rowNum)
	nameText := make([]driver.Value, rowNum)
	val := make([]driver.Value, rowNum)
	date := make([]driver.Value, rowNum)
	major := make([]driver.Value, rowNum)
	initalVal := 1.1
	for index := 0; index < rowNum; index++ {
		visitID[index] = index + 1
		nameText[index] = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
		val[index] = initalVal
		date[index] = time.Now().AddDate(0, index, 0)
		initalVal += 1.1
		if index == 0 {
			major[index] = "M-13"
		} else {
			major[index] = "SP-17"
		}
	}
	result, err := conn.BulkInsert(sqlText, rowNum, visitID, nameText, val, date)
	if err != nil {
		return err
	}
	rowsAffected, _ := result.RowsAffected()
	fmt.Printf("%d rows inserted: %v\n", rowsAffected, time.Now().Sub(t))
	return nil
}
```
the code is working without error

**Comment by sijms** [comment] 2022-04-30 14:45
> Greetings!
> 
> I have a similar problem: I constantly get an error like ORA-24381.
> 
> I noticed one interesting feature: if I execute the code using Bulk Insert many times, after some time it will still be executed without errors and the insertion of rows will be successful. Very strange behavior. But in 98 percent of cases, I always get the error ORA-24381.

the error you receive means that one of the record you pass to BulkInsert give error
you need to confirm that data not exceed column max value and not inserting null to non null column

if you insert row by row you will get the problematic row that make the error

**Comment by sijms** [comment] 2022-05-01 11:47
as the issue is not related to the driver I will close it

**Comment by j38890** [comment] 2022-05-02 10:03
Thx.
Pls replace the sqlText with “INSERT INTO GOORA_TEMP_VISIT(VISIT_ID, NAME, VAL, VISIT_DATE,MAJOR) VALUES(:1, :2, :3, :4, :5)” , and then add major array in bulkinsert method, the error msg should be returned.
It maybe because of the db charset? 

select * from nls_session_parameters;

NLS_LANGUAGE	SIMPLIFIED CHINESE
NLS_TERRITORY	CHINA
NLS_CURRENCY	￥
NLS_ISO_CURRENCY	CHINA
NLS_NUMERIC_CHARACTERS	.,
NLS_CALENDAR	GREGORIAN
NLS_DATE_FORMAT	DD-MON-RR
NLS_DATE_LANGUAGE	SIMPLIFIED CHINESE
NLS_SORT	BINARY
NLS_TIME_FORMAT	HH.MI.SSXFF AM
NLS_TIMESTAMP_FORMAT	DD-MON-RR HH.MI.SSXFF AM
NLS_TIME_TZ_FORMAT	HH.MI.SSXFF AM TZR
NLS_TIMESTAMP_TZ_FORMAT	DD-MON-RR HH.MI.SSXFF AM TZR
NLS_DUAL_CURRENCY	￥
NLS_COMP	BINARY
NLS_LENGTH_SEMANTICS	BYTE
NLS_NCHAR_CONV_EXCP	FALSE

**Comment by sijms** [comment] 2022-05-02 17:07
thank you I find the bug and fix it in new release

**Closed by sijms** 2022-05-02 17:07 UTC

**Comment by rolson-alister** [comment] 2022-05-04 09:14
Thank you very much!
In the new release, my floating error also disappeared and now everything works correctly and from the first time. Thanks!

**Comment by sijms** [comment] 2022-05-06 23:39
> 

sorry for my first suggestion but many times I wasting time search for issues then find the cause is related to misuse sql or driver so I need to confirm that at first

**Comment by sijms** [comment] 2022-05-06 23:39
> Thx. Pls replace the sqlText with “INSERT INTO GOORA_TEMP_VISIT(VISIT_ID, NAME, VAL, VISIT_DATE,MAJOR) VALUES(:1, :2, :3, :4, :5)” , and then add major array in bulkinsert method, the error msg should be returned. It maybe because of the db charset? select * from nls_session_parameters; NLS_LANGUAGE SIMPLIFIED CHINESE NLS_TERRITORY CHINA NLS_CURRENCY ￥ NLS_ISO_CURRENCY CHINA NLS_NUMERIC_CHARACTERS ., NLS_CALENDAR GREGORIAN NLS_DATE_FORMAT DD-MON-RR NLS_DATE_LANGUAGE SIMPLIFIED CHINESE NLS_SORT BINARY NLS_TIME_FORMAT HH.MI.SSXFF AM NLS_TIMESTAMP_FORMAT DD-MON-RR HH.MI.SSXFF AM NLS_TIME_TZ_FORMAT HH.MI.SSXFF AM TZR NLS_TIMESTAMP_TZ_FORMAT DD-MON-RR HH.MI.SSXFF AM TZR NLS_DUAL_CURRENCY ￥ NLS_COMP BINARY NLS_LENGTH_SEMANTICS BYTE NLS_NCHAR_CONV_EXCP FALSE
> […](#)

sorry for my first suggestion but many times I wasting time search for issues then find the cause is related to misuse sql or driver so I need to confirm that at first
