### ISSUE TITLE
Problem connecting to Oracle 9i

### ISSUE THREAD

**Issue by MichalisDBA** [sijms/go-ora#221] opened 2022-07-13 09:14 UTC
Hello.

I built the usql with your go-ora v1. I can connect to Oracle 10 Databases but still i can not connect to Oracle 9i. I get the same message.

error: the packet received is not data packet

I have the same problem as mentioned here

https://github.com/sijms/go-ora/issues/208

Is there something i can do to connect to Oracle 9i database?

**Comment by sijms** [comment] 2022-07-13 20:22
the problem I don't have this database version to test the program with it 
if you can share the log file it may help to identify the location of the problem

**Comment by MichalisDBA** [comment] 2022-07-14 07:14
There aren't any logs except from this output that usql produces based on your v1 go-ora.

Is there something i can do to produce a more verbose log?

**Comment by MichalisDBA** [comment] 2022-07-14 09:08
@sijms I sent you an e-mail at samyibraheem@gmail.com for the database. Please check it.

**Comment by sijms** [comment] 2022-07-14 09:15
thank you for help
I receive your email and i will start to download files and install database
you can create log file by add the following to database URL `oracle://user:pass@server/service_name?TRACE FILE=trace.log`

**Comment by sijms** [comment] 2022-07-18 15:13
I download the server and run first test
the problem  appear to me in login oracle 9i need special auth request
so i will test the original driver and see what is the correct auth request it send

**Comment by sijms** [comment] 2022-08-02 22:20
Now v1 can connect to database 9 successfully

but still there are a lot of work to do to avoid errors during execution of queries

**Comment by MichalisDBA** [comment] 2022-08-03 07:37
Hello. Wow great will try it. Should i expect error for example in DML queries? Will you create a release? I see version 1.2.1. I want to build usql project with your go-ora driver.

**Comment by sijms** [comment] 2022-08-03 08:23
still no release
first error i receive and work on it now when you call insert or update again after passing new parameter values
after finish all i will make new release

**Comment by sijms** [comment] 2022-08-04 19:47
now version 1.3.0 connect to server and do simple CRUD without errors

**Comment by MichalisDBA** [comment] 2022-08-04 19:58
Great will check it and inform you if anything comes up. Thank you very much!

**Comment by MichalisDBA** [comment] 2022-08-05 11:59
Hello.

I get an error upon connection

```
error: oracle: ORA-06550: line 22, column 9:
PLS-00553: character set name is not recognized
ORA-06550: line 0, column 0:
PL/SQL: Compilation unit analysis terminated
```

Our database has the character set to that of:
el8mswin1253 - MS Windows Code Page 1253 8-bit Latin/Greek

Is it a problem with your driver or something else?

**Comment by sijms** [comment] 2022-08-05 20:51
according to this URL [link](http://www.nazmulhuda.info/after-restart-of-database-suddenly-pls-00553-character-set-name-is-not-recognized-are-seen-in-the-alert-log) you try to connect before database is fully open

**Comment by sijms** [comment] 2022-08-05 20:53
also I make structure update to the package v1.3.1

**Comment by sijms** [comment] 2022-08-08 21:18
any news about the issue?

**Comment by MichalisDBA** [comment] 2022-08-08 21:25
I still haven't managed to connect. Our production database is up and running. I can connect with TOAD but not with usql build with your ora go driver. I will try again tomorrow and inform you.

**Comment by sijms** [comment] 2022-08-08 21:27
try and also if you can make some debuging and see which step is the cause of the issue

**Comment by sijms** [comment] 2022-08-09 12:36
comment line #494 in the file connection.go and test again it will work

**Comment by MichalisDBA** [comment] 2022-08-09 13:30
Yes now it works! Awsome, thank you very much! Will you create a conditional check for this on an upcoming release or i have to comment this line everytime i want to build the project from start? Just to note it down somewhere. Again thank you very much for your work.

**Comment by sijms** [comment] 2022-08-09 15:18
I will comment it in next release
i will close this issue as connection go successfully
if you get another problem just open a new issue

thanks for your help

**Closed by sijms** 2022-08-09 15:18 UTC
