### ISSUE TITLE
The Packet Received is Not Data Packet

### ISSUE THREAD

**Issue by marcoazevedo1976** [sijms/go-ora#256] opened 2022-10-10 14:54 UTC
Hi there,  
I'm facing this problem when executing a select with a Blob Column. The problem happens intermittently. When I run the code below, sometimes the problem happens sometimes not. Even running with the same record. The error message is "the packet received is not data packet". The database is Oracle 19c and the driver is github.com/sijms/go-ora/v2 v2.5.3 . The OS is Windows 10 pro.
This is the code:
```
        query := "select m.my_blob_column from my_table m where m.id = :1"

	row := n.db.QueryRow(query, id)
	if err := row.Err(); err != nil {
		log.Println("QueryRow", err) // The message "the packet received is not data packet" is shown here!
		return
	}

	var blob []byte
	err := row.Scan(&blob)

	if err != nil {
		log.Println("Scan", err)
                return
	}

```
Please let me know if you need more details.
Thanks!

**Comment by sijms** [comment] 2022-10-18 12:06
hi @marcoazevedo1976 
can you tell me exactly the size of the blob that you are reading

**Comment by marcoazevedo1976** [comment] 2022-10-18 13:04
Hi @sijms
The size is 323709 bytes.

**Comment by Bustel** [comment] 2022-10-20 19:19
I am having the exact same problem, also while retrieving blobs, also seemingly random.

**Comment by sijms** [comment] 2022-11-16 07:23
i get the error after inserting 7 mb file into blob 
insertion go ok
but reading sometimes ok and sometimes not

**Comment by sijms** [comment] 2022-11-16 18:00
after investigation I find some interesting results:
1- the problem is intermittent (not every run)
2- the problem occur on linux. not on MAC os. windows not tested
3- the problem is due to 0x00 add at the end of the packet which disrupt the packet structure
4- this leading 0 occur during blob chunk read at fixed chunk index

**Comment by sijms** [comment] 2022-11-17 11:22
what is your server version?

**Comment by marcoazevedo1976** [comment] 2022-11-17 13:33
Hi Samy,
Yes, Interesting results! 
Here the problem does not happen on Linux. Actually just on Windows 10 Pro, which is my development environment. I have one more additional information that I hope it helps: When I add tracelog into the connection string ("?trace file=/var/log/trace.log") the issue doesn't happen at all! 
So, just as a temporary workaround I added the trace log just when running on Windows 10 Pro (the development PCs). 
Many thanks for your assistance and let me know if you need more information!

**Comment by sijms** [comment] 2022-11-17 22:22
macOs has oracle server 12.2 ==> working
linux mint has oracle server 19.3 ==> not working
what is your oracle server version

**Comment by sijms** [comment] 2022-11-17 22:36
after long time investigation I find that this extra 0x00 byte is coming from the server itself and this occur at certain chunk and not every time.
sometimes 0x00 is sent ==> panic
sometime not sent ==> go normally

**Comment by sijms** [comment] 2022-11-17 23:26
I test now with windows 10 virtual machine on same linux host (linux mint oracle 19.3) ==> no error
so I think the problem is related linux itself not oracle server

**Comment by sijms** [comment] 2022-11-17 23:29
now I test on linux but using `real host ip` not `localhost` and no error occur with linux also
so the problem is network related and package is bug free in relation to this issue

**Comment by sijms** [comment] 2022-11-17 23:32
I will close the issue now and if you find something interesting I will open again for further investigation

**Closed by sijms** 2022-11-17 23:32 UTC
